language: android

env:
  matrix:
    - ANDROID_TARGET=android-22 ANDROID_ABI=armeabi-v7a

notifications:
  email:
    - phongnguyen180993@gmail.com

android:
  components:
    - tools
    - tools
    - build-tools-28.0.3
    - platform-tools
    - android-19
    - android-28
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-28

script:
  - ./gradlew assembleDebug