language: android

env:
  matrix:
    - ANDROID_TARGET=android-22 ANDROID_ABI=armeabi-v7a

notifications:
  slack: videosocialnetwork:ber6OdxZTeh4aDV9DsDNMFBH
  email:
    - phongnguyen180993@gmail.com

android:
  components:
    - tools
    - tools
    - build-tools-28.0.3
    - platform-tools
    - android-19
    - android-29
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-29

before_script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew connectedAndroidTest